name: Compile Checks on PRs
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
#    types: [opened, synchronize, reopened]
jobs:
  mvn-compile:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          cd $GITHUB_WORKSPACE && pwd
          if [ ! -d .git ]; then git init; git config user.email "minrong716@gmail.com"; git config user.name "wenminrong"; git add --all && git commit -q -m "Only fix mvn goals for github workflow"; fi
          if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc; find info with https://github.com/cskefu/cskefu/issues/688"; exit 1; fi
          java -version && mvn -version
          $GITHUB_WORKSPACE/public/plugins/scripts/install-all.sh
          cd $GITHUB_WORKSPACE/contact-center && ./admin/compile.sh
